### ISSUE TITLE
Container has one extra page (specified page number + 1)

### ISSUE THREAD

**Issue by tszekely** [stickyroll/react-stickyroll#4] opened 2018-12-05 14:08 UTC
First of all thank you for your work on this library, it's a lifesaver for me right now :)
I've encountered a weird issue and would like to have your input on it (and preferably a fix if possible).

**Describe the bug**
Setting the `pages` property to `n` sets the container height to `(n+1) * 100vh` and the last page seems to last twice as long as the others. (example: I've set it to 3, and my container is 400vh tall). 
I've also noticed this weird bug on the demo page (https://stickyroll.netlify.com) where the page numbers are `page + 1`, resulting in things like "page 4 of 3", I'm guessing it could be originating in the same problem.

**To Reproduce**
I guess the description makes it clear enough, if not I'll fill this. Version is 1.0.0.

**Expected behavior**
The container height should be `pages * 100vh` tall and the last page should be equal to the others.

**Desktop (please complete the following information):**
 - OS: macOS Mojave
 - Browser: Chrome
 - Version: 70.0.3538.110

**Comment by pixelass** [comment] 2018-12-06 21:08
Thank you for trying stickyroll and reporting this issue.
This is the intended behavior. 

Let's start with 1 page. 

To allow scrolling one page we need to add `100vh`. Therefore 1 page is `200vh` high.
Every other page adds 100vh. Therefore 3 pages have a height of `400vh`.

I also cannot reproduce that the last page is longer. It's really simple math but maybe I'm wrong. Maybe you can create a codesandbox example to show this issue (stater templates are linked in the readme).  

A good way to test this, is to use the spacebar. One tap should scroll approximately one page. So after 3 spacebar taps you should be at the end of page 3 (or really close).

When using pagers/anchors, there is an extra link/target to allow jumping to the end. This is also intended.

Thank you for pointing out the errors on the demo page. This was due to an API change which added `pageIndex [0]` aside `page [1]`. Both are available, one 0 based the other 1 based. 

I am currently working on a better documentation which will resolve this issue.


I will close this issue since I don't see anything to fix right now. 
Feel free to reopen if you have an example or are sure there is a difference. I will try to further investigate.

**Comment by pixelass** [comment] 2018-12-06 23:42
Can you give me more information on this issue?

Did you use the `anchors` option?

**Comment by pixelass** [comment] 2018-12-06 23:51
I can only reproduce it when `factor={>1|<1}` is used in combination with `anchors`.

**Comment by pixelass** [comment] 2018-12-07 03:02
the issue I experienced is fixed and available as new version.

In the process I also deployed a first version of the new documentation

https://stickyroll.github.io/react-stickyroll/

I will close this issue since I don't see anything to fix right now.
Feel free to reopen if you have an example or are sure there is a difference. I will try to further investigate.

**Closed by pixelass** 2018-12-07 03:02 UTC
